const DB = [
    {
      id: 1,
      title: "Renaissance Genius: Leonardo da Vinci",
      slug: "leonardo-da-vinci",
      category: "Art & History",
      image: "https://hips.hearstapps.com/hmg-prod/images/portrait-of-leonardo-da-vinci-1452-1519-getty.jpg?crop=1xw:1.0xh;center,top&resize=640:*",
      tags: ["Renaissance", "painting", "sculpture", "architecture", "science"],
      content: "Leonardo da Vinci was an Italian polymath of the Renaissance period, active as a painter, sculptor, architect, musician, scientist, inventor, military engineer, and writer. His genius, perhaps unmatched to this day, epitomized the Renaissance humanist ideal. Leonardo is widely considered one of the greatest painters of all time. His Mona Lisa and The Last Supper are two of the world's most famous and most analyzed works of art, and his notebooks reveal a mind of extraordinary inventiveness. Leonardo's curiosity was boundless, and his work was often far ahead of its time. He conceived ideas that were centuries ahead of their time, such as helicopters, tanks, and solar power.",
      date: '2024-02-15',
    },
    {
      id: 2,
      title:       "The Footballing Maestro: Lionel Messi",
      slug:        "lionel-messi",
      category: "Sports",
      image:     "https://static01.nyt.com/images/2019/04/16/sports/16onsoccerweb-2/merlin_153612873_5bb119b9-8972-4087-b4fd-371cab8c5ba2-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
      tags:       ["football", "soccer", "Argentina", "FC Barcelona", "Paris Saint-Germain"],
      content: "Lionel Andrés Messi, often considered one of the greatest footballers of all time, is an Argentine professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and captains the Argentina national team. Born and raised in Rosario, Santa Fe, Messi began his senior career with Barcelona in 2004, where he spent 17 years. During his time at Barcelona, he won a record six Ballon d'Or awards and a record six European Golden Shoes. He has also won a record seven Ballon d'Or awards overall. In 2021, he left Barcelona to join Paris Saint-Germain.",
      date: '2024-02-15',
    },
    {
      id: 3,
      title: "The Icon of Anti-Apartheid: Nelson Mandela",
      slug: "nelson-mandela",
      category: "History & Politics",
      image: "https://static01.nyt.com/images/2018/07/08/sunday-review/08Mandela-Images-slide-3GG5/08Mandela-Images-slide-3GG5-superJumbo-v2.jpg",
      tags: ["South Africa", "anti-apartheid", "Nobel Peace Prize"],
      content: "Nelson Rolihlahla Mandela was a South African anti-apartheid revolutionary, politician, and philanthropist who served as President of South Africa from 1994 to 1999. He was the country's first black head of state and the first elected in a fully representative democratic election. His government focused on dismantling the legacy of apartheid and fostering racial reconciliation. Mandela was born in Mvezo, Transkei, on 18 July 1918, to the royal family of the Thembu people. He studied law at the University of Fort Hare and the University of Witwatersrand. After joining the African National Congress (ANC) in 1942, he became involved in its campaign of defiance against white minority rule. Imprisoned for 27 years, Mandela became an international icon of resistance against apartheid. After his release in 1990, he and de Klerk negotiated an end to apartheid and held the country's first multiracial democratic elections. Mandela died on 5 December 2013, aged 95.",
      date: '2024-02-15',
    },
    {
      id: 4,
      title: "The Queen of Pop: Madonna",
      slug: "madonna",
      category: "Music",
      image: "https://images.radio.com/aiu-media/madonna-fefe4977-59e3-4ffe-8851-d189649ae527.jpg?width=800",
      tags: ["pop music", "singer", "songwriter", "actress"],
      content: "Madonna Louise Ciccone is an American pop singer, songwriter, and actress who has been dubbed the 'Queen of Pop' since the 1980s. Known for her constant reinvention and versatility in music production, songwriting, and visual presentation, Madonna has been a cultural icon for decades. With hits like 'Like a Virgin,' 'Material Girl,' and 'Vogue,' she has sold over 300 million records worldwide, making her the best-selling female recording artist of all time according to the Guinness World Records. Madonna's influence extends beyond music into fashion and social activism. She has won seven Grammy Awards and continues to inspire artists worldwide with her fearless innovation.",
      date: '2024-02-15',
    },
    {
      id: 5,
      title: "King of Rock and Roll: Elvis Presley",
      slug: "elvis-presley",
      category: "Music",
      image: "https://i.scdn.co/image/ab6761610000e5eb9a93e273380982dff84c0d7c",
      tags: ["rock and roll", "singer", "actor", "Graceland"],
      content: "Elvis Aaron Presley, often referred to as the 'King of Rock and Roll,' was an American singer and actor whose influence on music and pop culture was unprecedented. Born in Tupelo, Mississippi, in 1935, Elvis popularized rock and roll music with hits like 'Heartbreak Hotel,' 'Hound Dog,' and 'Jailhouse Rock.' With his charismatic stage presence, unique voice, and iconic style, he became a global sensation. Elvis sold over 500 million records worldwide, making him one of the best-selling solo artists in history. He passed away in 1977 at his home in Graceland, Memphis, but his legacy remains timeless.",
      date: '2024-02-15',
    },
    {
      id: 6,
      title: "The Basketball Legend: Michael Jordan",
      slug: "michael-jordan",
      category: "Sports",
      image: "https://cdn.nba.com/manage/2021/08/michael-jordan-looks.jpg",
      tags: ["basketball", "NBA", "Chicago Bulls", "GOAT"],
      content: "Michael Jeffrey Jordan, often referred to as 'MJ,' is an American former professional basketball player widely regarded as one of the greatest basketball players of all time. Born in 1963 in Brooklyn, New York, he led the Chicago Bulls to six NBA championships during the 1990s and won five MVP awards. Known for his competitive drive and incredible athleticism, Jordan redefined the sport and became a global icon. Off the court, he has been a successful entrepreneur, owning the Charlotte Hornets and launching the Air Jordan brand with Nike.",
      date: '2024-02-15',
    },
    {
      id: 7,
      title: "The Voice of a Generation: Bob Dylan",
      slug: "bob-dylan",
      category: "Music",
      image: "https://cdn.britannica.com/91/197591-050-E90418AF/Bob-Dylan-Bringing-It-All-Back-Home-1965.jpg",
      tags: ["folk music", "songwriter", "Nobel Prize", "activism"],
      content: "Bob Dylan, born Robert Allen Zimmerman in 1941, is an American singer-songwriter and one of the most influential musicians of all time. Known for his profound lyrics and distinctive voice, Dylan's songs like 'Blowin' in the Wind' and 'The Times They Are A-Changin'' became anthems of the civil rights and anti-war movements in the 1960s. Dylan has won numerous accolades, including the Nobel Prize in Literature in 2016 for creating 'new poetic expressions within the great American song tradition.' His career spans over six decades, and he continues to inspire with his art and activism.",
      date: '2024-02-15',
    },
    {
      id: 8,
      title: "The Iron Lady: Margaret Thatcher",
      slug: "margaret-thatcher",
      category: "Politics",
      image: "https://cdn.britannica.com/16/172216-050-B5568602/Prime-Minister-Margaret-Thatcher.jpg?w=400&h=225&c=crop",
      tags: ["Prime Minister", "UK politics", "Conservative Party", "Cold War"],
      content: "Margaret Hilda Thatcher, known as the 'Iron Lady,' was the Prime Minister of the United Kingdom from 1979 to 1990. She was the first woman to hold this position and was the leader of the Conservative Party. Born in 1925 in Grantham, England, Thatcher implemented sweeping economic reforms, including privatization and deregulation, which transformed the UK economy. Her leadership during the Cold War and her strong stance against communism earned her a prominent place in world history. Thatcher passed away in 2013, leaving a complex but enduring legacy.",
      date: '2024-02-15',
    },
    {
      id: 9,
      title: "The King of Bollywood: Shah Rukh Khan",
      slug: "shah-rukh-khan",
      category: "Film & Entertainment",
      image: "https://variety.com/wp-content/uploads/2024/08/Shah-Rukh-Khan-Locarno1.jpg",
      tags:["none"],
      content:"Not available",
      date: '2024-02-15',
    }
]
export const quotes = [
  { saying: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.", sayer: "Steve Jobs" },
  { saying: "The future belongs to those who believe in the beauty of their dreams.", sayer: "Eleanor Roosevelt" },
  { saying: "Strive not to be a success, but rather to be of value.", sayer: "Albert Einstein" },
  { saying: "Be the change that you wish to see in the world.", sayer: "Mahatma Gandhi" },
  { saying: "The best time to plant a tree was 20 years ago. The second best time is today.", sayer: "Chinese Proverb" },
  { saying: "It always seems impossible until it's done.", sayer: "Nelson Mandela" },
  { saying: "Your time is limited, so don't waste it living someone else's life.", sayer: "Steve Jobs" },
  { saying: "The only person you are destined to become is the person you decide to be.", sayer: "Ralph Waldo Emerson" },
  { saying: "Believe you can and you're halfway there.", sayer: "Theodore Roosevelt" },
  { saying: "Don't watch the clock; do what it does. Keep going.", sayer: "Sam Levenson" },
  { saying: "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.", sayer: "Robert Frost" },
  { saying: "The greatest glory in living lies not in never falling, but in rising every time we fall.", sayer: "Nelson Mandela" },
  { saying: "Life is what happens when you're busy making other plans.", sayer: "John Lennon" },
  { saying: "The only thing necessary for the triumph of evil is for good men to do nothing.", sayer: "Edmund Burke" },
  { saying: "In three words I can sum up everything I've learned about life: it goes on.", sayer: "Robert Frost" },
  { saying: "The difference between ordinary and extraordinary is that little extra.", sayer: "Jimmy Johnson" },
  { saying: "The mind is everything. What you think you become.", sayer: "Buddha" },
  { saying: "Happiness is not something ready made. It comes from your own actions.", sayer: "Dalai Lama" },
  { saying: "The only way to do great work is to love what you do.", sayer: "Steve Jobs" },
  { saying: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", sayer: "Helen Keller" },
  { saying: "It is never too late to be what you might have been.", sayer: "George Eliot" },
  { saying: "What you get by achieving your goals is not as important as what you become by achieving your goals.", sayer: "Zig Ziglar" },
  { saying: "The journey of a thousand miles begins with a single step.", sayer: "Lao Tzu" },
  { saying: "You miss 100% of the shots you don't take.", sayer: "Wayne Gretzky" },
  { saying: "I have not failed. I've just found 10,000 ways that won't work.", sayer: "Thomas Edison" },
  { saying: "If you can dream it, you can achieve it.", sayer: "Zig Ziglar" },
  { saying: "The only limit to our realization of tomorrow will be our doubts of today.", sayer: "Franklin D. Roosevelt" },
  { saying: "Don't be afraid to give up the good to go for the great.", sayer: "John D. Rockefeller" },
  { saying: "Challenges are what make life interesting. Overcoming them is what makes life meaningful.", sayer: "Joshua Marine" },
  { saying: "The best revenge is massive success.", sayer: "Frank Sinatra" },
  { saying: "Life is really simple, but we insist on making it complicated.", sayer: "Confucius" },
  { saying: "The only source of knowledge is experience.", sayer: "Albert Einstein" },
  { saying: "It's not what happens to you, but how you react to it that matters.", sayer: "Epictetus" },
  { saying: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.", sayer: "Vince Lombardi" },
  { saying: "If you want to live a happy life, tie it to a goal, not to people or things.", sayer: "Albert Einstein" },
  { saying: "The greatest weapon against stress is our ability to choose one thought over another.", sayer: "William James" },
  { saying: "Success is not final, failure is not fatal: it is the courage to continue that counts.", sayer: "Winston Churchill" },
  { saying: "You are never too old to set another goal or to dream a new dream.", sayer: "C.S. Lewis" },
  { saying: "What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.", sayer: "Ralph Waldo Emerson" },
  { saying: "The most important thing is to enjoy your life – to be happy – it's all that matters.", sayer: "Audrey Hepburn" },
  { saying: "It does not matter how slowly you go as long as you do not stop.", sayer: "Confucius" },
  { saying: "Believe in yourself and you're halfway there.", sayer: "Theodore Roosevelt" },
  { saying: "You become what you believe.", sayer: "Oprah Winfrey" },
  { saying: "The only way to do great work is to love what you do.", sayer: "Steve Jobs" },
  { saying: "It's not about perfect. It's about effort.", sayer: "Jillian Michaels" },
  { saying: "Our greatest glory is not in never falling, but in rising every time we fall.", sayer: "Confucius" },
    { saying: "The best view comes after the hardest climb.", sayer: "Unknown" },
    { saying: "Every accomplishment starts with the decision to try.", sayer: "Unknown" },
    { saying: "Don't let yesterday take up too much of today.", sayer: "Will Rogers" },
    { saying: "The harder you work for something, the greater you’ll feel when you achieve it.", sayer: "Unknown" },
    { saying: "If you’re not willing to risk the usual, you will have to settle for the ordinary.", sayer: "Jim Rohn" },
    { saying: "The only thing standing between you and your dream is the will to try and the belief that it is actually possible.", sayer: "Joel Brown" }
];

export default DB; 